### PR TITLE
Fix static content

### PR DESCRIPTION
**Pull request by bedeoverend**
Fixes being able to use static content to initially set content into buffer

### CODE REVIEW

**Comment by seaneking** [comment]
I'd already converted simpla-img to v2 and updated the setCallback stuff? Did you not pull down latest?

**Comment by bedeoverend** [comment]
Yeah, see the final merge commit. Just cleaned up a few bits that weren't needed given the latest element-behavior, and static url stuff

**Comment by bedeoverend** [comment]
Oh - no this branch was around from pre your commits

**Comment by seaneking** [comment]
Yep saw that as soon as I made that comment hahaha

**Pull request merged**
